### ISSUE TITLE
This project is copied from elpheria/rpc-websockets

### ISSUE THREAD

**Issue by mkozjak** [zo-el/msgpack-rpc-websockets#1]
Can you double-check your license?
Where are the contents from this one? https://github.com/elpheria/rpc-websockets/blob/master/LICENSE

https://choosealicense.com/licenses/lgpl-3.0
("_Copyright and license notices must be preserved."_)

Are you working for Holochain?

**Comment by mkozjak** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/3506172/129534043-ec6d64ec-cf02-40c8-9cef-e1fe32f2f32d.png">

You even copied this one, and your license is not LGPL v3.0. Please revisit all this ASAP.

**Comment by zo-el** [comment]
Hi @mkozjak, thanks for point this all out. Can I get a little more guidance on what I need to be changing?

**Comment by mkozjak** [comment]
Hi, @zo-el, please use the internet for guidance. If you need any support, I'm available for contracting work. Also feel free to send me a request for the review once you make the changes.

**Comment by mkozjak** [comment]
cc #2

**Comment by zo-el** [comment]
ok, So I cleaned up the branches and deleted the tags. Feel free to close this issue when you look into it
